//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ARMADatabaseEntities : DbContext
    {
        public ARMADatabaseEntities()
            : base("name=ARMADatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<be_modules> be_modules { get; set; }
        public DbSet<be_roles> be_roles { get; set; }
        public DbSet<be_users> be_users { get; set; }
        public DbSet<Mall> Malls { get; set; }
        public DbSet<mk_about> mk_about { get; set; }
        public DbSet<mk_appusers> mk_appusers { get; set; }
        public DbSet<mk_categories> mk_categories { get; set; }
        public DbSet<mk_codes> mk_codes { get; set; }
        public DbSet<mk_contactus> mk_contactus { get; set; }
        public DbSet<mk_discount_type> mk_discount_type { get; set; }
        public DbSet<mk_favourites> mk_favourites { get; set; }
        public DbSet<mk_feeds> mk_feeds { get; set; }
        public DbSet<mk_follows> mk_follows { get; set; }
        public DbSet<mk_gcm_tokens> mk_gcm_tokens { get; set; }
        public DbSet<mk_images> mk_images { get; set; }
        public DbSet<mk_inquiries> mk_inquiries { get; set; }
        public DbSet<mk_items> mk_items { get; set; }
        public DbSet<mk_items_attributes_detail> mk_items_attributes_detail { get; set; }
        public DbSet<mk_items_attributes_header> mk_items_attributes_header { get; set; }
        public DbSet<mk_likes> mk_likes { get; set; }
        public DbSet<mk_ratings> mk_ratings { get; set; }
        public DbSet<mk_reviews> mk_reviews { get; set; }
        public DbSet<mk_shop_followers> mk_shop_followers { get; set; }
        public DbSet<mk_shops> mk_shops { get; set; }
        public DbSet<mk_sub_categories> mk_sub_categories { get; set; }
        public DbSet<mk_touches> mk_touches { get; set; }
        public DbSet<mk_transaction_detail> mk_transaction_detail { get; set; }
        public DbSet<mk_transaction_header> mk_transaction_header { get; set; }
        public DbSet<mk_transaction_status> mk_transaction_status { get; set; }
        public DbSet<be_permissions> be_permissions { get; set; }
        public DbSet<be_role_access> be_role_access { get; set; }
        public DbSet<ci_sessions> ci_sessions { get; set; }
    }
}
