//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class be_modules
    {
        public int module_id { get; set; }
        public string module_name { get; set; }
        public string module_desc { get; set; }
        public string module_icon { get; set; }
        public int ordering { get; set; }
        public short is_show_on_menu { get; set; }
        public int group_id { get; set; }
        public string group_name { get; set; }
        public string group_icon { get; set; }
        public short group_has_child { get; set; }
    }
}
