//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class be_users
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_email { get; set; }
        public string user_pass { get; set; }
        public int role_id { get; set; }
        public short is_owner { get; set; }
        public short is_shop_admin { get; set; }
        public int shop_id { get; set; }
        public System.DateTime added { get; set; }
        public short status { get; set; }
    }
}
