//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class mk_appusers
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string about_me { get; set; }
        public string delivery_address { get; set; }
        public string billing_address { get; set; }
        public string profile_photo { get; set; }
        public string background_photo { get; set; }
        public short is_banned { get; set; }
        public short status { get; set; }
        public System.DateTime added { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    }
}
