//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class mk_feeds
    {
        public int id { get; set; }
        public int shop_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public short is_published { get; set; }
        public System.DateTime added { get; set; }
        public string title_ar { get; set; }
        public string description_ar { get; set; }
    }
}
