//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class mk_gcm_tokens
    {
        public int id { get; set; }
        public string device_id { get; set; }
        public string os_type { get; set; }
        public string reg_id { get; set; }
        public System.DateTime added { get; set; }
    }
}
