//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class mk_images
    {
        public int id { get; set; }
        public int parent_id { get; set; }
        public string type { get; set; }
        public string path { get; set; }
        public string width { get; set; }
        public string height { get; set; }
        public string description { get; set; }
    }
}
