//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class mk_shops
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string coordinate { get; set; }
        public double lat { get; set; }
        public double lng { get; set; }
        public string paypal_email { get; set; }
        public string paypal_environment { get; set; }
        public string paypal_appid_live { get; set; }
        public string paypal_merchantname { get; set; }
        public string paypal_customerid { get; set; }
        public string paypal_ipnurl { get; set; }
        public string paypal_memo { get; set; }
        public string bank_account { get; set; }
        public string bank_name { get; set; }
        public string bank_code { get; set; }
        public string branch_code { get; set; }
        public string swift_code { get; set; }
        public string cod_email { get; set; }
        public string stripe_publishable_key { get; set; }
        public string stripe_secret_key { get; set; }
        public string currency_symbol { get; set; }
        public string currency_short_form { get; set; }
        public string sender_email { get; set; }
        public System.DateTime added { get; set; }
        public short status { get; set; }
        public short paypal_enabled { get; set; }
        public short stripe_enabled { get; set; }
        public short cod_enabled { get; set; }
        public short banktransfer_enabled { get; set; }
        public string name_ar { get; set; }
        public string description_ar { get; set; }
    }
}
