//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class mk_sub_categories
    {
        public int id { get; set; }
        public int cat_id { get; set; }
        public int shop_id { get; set; }
        public string name { get; set; }
        public int is_published { get; set; }
        public int ordering { get; set; }
        public System.DateTime added { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    }
}
