//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class mk_transaction_header
    {
        public int id { get; set; }
        public int shop_id { get; set; }
        public int user_id { get; set; }
        public string payment_trans_id { get; set; }
        public double total_amount { get; set; }
        public string delivery_address { get; set; }
        public string billing_address { get; set; }
        public short transaction_status { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string payment_method { get; set; }
        public System.DateTime added { get; set; }
    }
}
