//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class mk_transaction_detail
    {
        public int id { get; set; }
        public int transaction_header_id { get; set; }
        public int shop_id { get; set; }
        public int item_id { get; set; }
        public string item_name { get; set; }
        public string item_attribute_id { get; set; }
        public string item_attribute { get; set; }
        public double unit_price { get; set; }
        public int qty { get; set; }
        public double discount_percent { get; set; }
        public System.DateTime added { get; set; }
        public string platform { get; set; }
    }
}
